### ISSUE TITLE
Recycleview Misplaced

### ISSUE THREAD

**Issue by dzkmrn** [Factha-Bangkit-Capstone/mobile-factha#37]
There is a little bit of misplaced in displaying the recycleview in ArticleFragment.kt, where the very bottom of recycleview item is covered by bottomnavbar. Therefore we cannot see it. 

<img width="274" alt="Issue_Mobile" src="https://github.com/Factha-Bangkit-Capstone/mobile-factha/assets/99970931/51c7426b-30ba-4805-848a-fa3170022aa6">

**Comment by izamul** [comment]
thanks
